/**
 * Furina (furina) skin hooks - DRAFT generated by scripts/dsh-skin-migrate-v2.mjs.
 *
 * TODO: manual review required before this file ships (issue #506). This
 * is a scaffold, not a verified port: read every TODO below, test against
 * the skin-center hooks runtime (contract x-org.linxin666.skin-center/v1alpha1),
 * then delete this header comment.
 *
 * Auto-migrated by the codemod (no hook code needed):
 *  - backdrop artwork + light/dark readability scrims ->
 *    contributes.backgroundMedia in skin.json. The skin-center owns the
 *    theme switch and the background-occlusion control now; the v1
 *    MutationObserver scrim swap is intentionally dropped.
 *  - stylesheet scoping -> html[data-dsh-skin="furina"] (loader-owned);
 *    the v1 body attribute is never written by v2 skins.
 *
 * TODO manual port:
 *  1. favicon injection - drafted below from the v1 bundle constant;
 *     verify the asset URL base (ctx.assetBase) and the replace/restore
 *     semantics against any pre-existing favicon link.
 */

export default function defineSkinHooks() {
  return {
    apply(ctx) {
      // TODO(review): favicon port. v1 injected a <link rel="icon"> with an
      // inline SVG; the codemod extracted it to assets/whale-icon.png.
      const favicon = document.createElement('link')
      favicon.rel = 'icon'
      favicon.type = 'image/svg+xml'
      favicon.href = ctx.assetBase + '/assets/whale-icon.png'
      document.head.append(favicon)
      ctx.onCleanup(() => favicon.remove())
    },
  }
}
